--- #YAML:1.0
name:                Net-Server-Framework
version:             1.2
abstract:            an event driven infrastructure around Net::Server
license:             ~
author:              
    - Lenz Gschwendtner <lenz@springtimesoft.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Crypt::CBC:                    0
    Data::FormValidator:           0
    Data::Serializer:              0
    DBI:                           0
    Digest::MD5:                   0
    MIME::Base64:                  0
    Net::Server:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
